<div class="container admin grid-admin">

    <nav class="bg-white rounded shadow-sm pt-4 mx-auto pe-4">
        <ul class="">
            <li class="mb-3"><a href="#" class="active-nav"><i class="fas fa-newspaper me-2"></i> Gestion des articles</a></li>
            <li class="mb-3"><a href="#"><i class="fas fa-tags me-2"></i> Gestion des catégories</a></li>
            <li class="mb-3"><a href="#"><i class="fas fa-users me-2"></i> Gestion des auteurs</a></li>
        </ul>
    </nav>
    
    <div>
        <h1 class="text-center mb-5">Gestion des articles</h1>
        <a href="index.php?page=create" class="btn btn-info my-2"><i class="fas fa-plus pe-2"></i>Créer un article</a>
        <table class="table table-striped bg-white">
            <thead class="bg-dark text-light">
                <tr>
                    <th>ID</th>
                    <th>Création</th>
                    <th>Titre</th>
                    <th>Auteur</th>
                    <th>Catégorie</th>
                    <th class="text-end">Opérations</th>
                </tr>
             </thead>
            <tbody>
                <?php foreach ($posts as $post): ?>
                <tr>
                    <!-- ID  -->
                    <td class="fw-bold"><?= htmlspecialchars($post['id']) ?></td>
                    <!-- DATE  -->
                    <td><em><?= htmlspecialchars($post['created_at']) ?></em></td>
                    <!-- ARTICLE URL + TITRE  -->
                    <td><?= substr(htmlspecialchars($post['title']), 0, 25) ?> [...]</td>
                    <!-- AUTEUR  -->
                    <td><?= htmlspecialchars($post['firstname'])." ".htmlspecialchars($post['lastname']) ?></td>
                    <!-- CATEGORIE  -->
                    <td><?= htmlspecialchars($post['category']) ?></td>
                    <!-- OPERATIONS  -->
                    <td class="col-3 text-end">
                        <!-- DETAILS ARTICLE  -->
                        <a href="index.php?page=post&id=<?= htmlspecialchars($post['id']) ?>" class="link-info mx-1" title="Détails de l'article"><i class="fas fa-search-plus fs-3"></i></a>
                        <!-- EDITION ARTICLE  -->
                        <a href="index.php?page=edit&id=<?= htmlspecialchars($post['id']) ?>" id="edit_data" class="link-warning mx-1" title="Modification de l'article"><i class="fas fa-edit fs-3"></i></a>
                        <!-- SUPPRESSION ARTICLE  -->
                        <a href="" id="delete_data" class="link-danger mx-1" title="Suppression de l'article"><i class="fas fa-trash fs-3"></i></a>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <span>Liste des posts classés par ordre chronologique inversé (<b><?= htmlspecialchars($total['total']) ?> <?= ($total['total'] <= 1) ? "article" : "articles" ; ?> au total</b>)</span>
    </div>
</div>

<!-- MODAL -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                Voulez-vous vraiment supprimer cet article ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<script>
    $('#exampleModalCenter').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })
</script>