<div class="container edit grid-admin">

    <nav class="bg-white rounded shadow-sm pt-4 mx-auto pe-4">
        <ul class="">
            <li class="mb-3"><a href="#" class="active-nav"><i class="fas fa-newspaper me-2"></i> Gestion des articles</a></li>
            <li class="mb-3"><a href="#"><i class="fas fa-tags me-2"></i> Gestion des catégories</a></li>
            <li class="mb-3"><a href="#"><i class="fas fa-users me-2"></i> Gestion des auteurs</a></li>
        </ul>
    </nav>
    
    <div>
        
        <!-- FORMULAIRE  -->
        <form class="bg-white rounded p-3" method="POST">
            <!-- SUCCESS -->
            <div class="container-msg">
                <?php if(!empty($message['success'])): ?>
                    <div class="success-msg">
                    <?php foreach($message as $key => $msg): ?>
                        <?= $msg ?>
                    <?php endforeach ?>
                    </div>
                <?php endif ?>
            </div>     
            <h1 class="text-center my-1">Créer un article</h1>

            <div class="row mb-3">
                <!-- CATEGORIE DE L'ARTICLE  -->
                <div class="col">
                    <label for="category">Catégorie</label>
                    <select class="form-control" id="category" name="category">
                        <option>Choisir une catégorie</option>
                    <?php foreach($categories as $category): ?>
                        <option value="<?= ($category['category']) ?>"><?= htmlspecialchars($category['category']) ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
                <div class="col">
                    <label for="author">Auteur</label>
                    <select class="form-control" id="category" name="category">
                    <option>Choisir un auteur</option>
                    <?php foreach($authors as $author): ?>
                        <option value="<?= $author['id'] ?>"><?= htmlspecialchars($author['firstname'])." ".htmlspecialchars($author['lastname']) ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
            </div>
            
            <!-- AUTEUR DE L'ARTICLE  -->
            <label for="title">Titre </label>
            <input type="text" class="form-control" name="title" value="<?= (isset($_POST['title'])) ? $_POST['title'] : '' ?>">
            <!-- ERREUR -->
            <div class="container-msg">
                <?php if(!empty($message['error']['title'])): ?>
                    <span class="text-danger">
                    <?php foreach($message as $key => $msg): ?>
                        * <?= $msg['title'] ?>
                    <?php endforeach ?>
                    </span>
                <?php endif ?>
            </div>     
            
            <!-- CONTENU DE L'ARTICLE  -->
            <div class="form-group">
                <label for="content">Contenu de l'article</label>
                <textarea class="form-control" id="content" name="content" rows="6"><?= (isset($_POST['content'])) ? $_POST['content'] : '' ?></textarea>
                  <!-- ERREUR -->
            <div class="container-msg">
                <?php if(!empty($message['error']['content'])): ?>
                    <span class="text-danger">
                    <?php foreach($message as $key => $msg): ?>
                        * <?= $msg['content'] ?>
                    <?php endforeach ?>
                    </span>
                <?php endif ?>
            </div>     
            </div>

            <button type="submit" name="submit" class="btn btn-dark mt-2">Créer l'article</button>

        </form>
    </div>
</div>