<div class="container edit grid-admin">

    <nav class="bg-white rounded shadow-sm pt-4 mx-auto pe-4">
        <ul class="">
            <li class="mb-3"><a href="#" class="active-nav"><i class="fas fa-newspaper me-2"></i> Gestion des articles</a></li>
            <li class="mb-3"><a href="#"><i class="fas fa-tags me-2"></i> Gestion des catégories</a></li>
            <li class="mb-3"><a href="#"><i class="fas fa-users me-2"></i> Gestion des auteurs</a></li>
        </ul>
    </nav>
    
    <div>
        <h1 class="text-center mb-5">Créer un article</h1>

        <!-- FORMULAIRE  -->
        <form class="bg-white rounded p-3" action="index.php?page=create" method="POST">

            <div class="container-msg my-2">

                <!-- MESSAGE ERRORS  -->
                <?php if(!empty($message['error'])): ?>
                <div class="alert alert-danger text-center" id="" role="alert">

                    <?php foreach($message as $key => $msg): ?>
                        <?= $msg ?>
                    <?php endforeach ?>

                </div>
                <?php endif ?>

                <!-- MESSAGE SUCCESS  -->
                <?php if(!empty($message['success'])): ?>
                <div class="alert alert-success text-center" role="alert">

                    <?php foreach($message as $key => $msg): ?>
                        <?= $msg ?>
                    <?php endforeach ?>

                </div>
                <?php endif ?>

            </div>

            <div class="row mb-3">
                <!-- CATEGORIE DE L'ARTICLE  -->
                <div class="col">
                    <label for="category">Catégorie</label>
                    <select class="form-control" id="category" name="category">
                    <?php foreach($posts as $category): ?>
                        <option value="<?= ($category['category']) ?>"><?= htmlspecialchars($category['category']) ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
                <div class="col">
                    <label for="author">Auteur</label>
                    <select class="form-control" id="category" name="category">
                    <?php foreach($posts as $authors): ?>
                        <option value="<?= $authors['id'] ?>"><?= htmlspecialchars($authors['firstname'])." ".htmlspecialchars($authors['lastname']) ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
            </div>
            
            <!-- AUTEUR DE L'ARTICLE  -->
            <label for="title">Titre</label>
            <input type="text" class="form-control mb-3" name="input_title" value="<?= (isset($_POST['input_title'])) ? $_POST['input_title'] : '' ?>">
            
            <!-- CONTENU DE L'ARTICLE  -->
            <div class="form-group">
                <label for="content">Contenu de l'article</label>
                <textarea class="form-control" id="content" name="input_content" rows="6"><?= (isset($_POST['input_content'])) ? $_POST['input_content'] : '' ?></textarea>
            </div>

            <button type="submit" name="submit" class="btn btn-dark mt-5">Créer l'article</button>

        </form>
    </div>
</div>