<div class="container">
    
    <!-- Chemin d'arianne -->
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.php">Accueil</a></li>
            <li class="breadcrumb-item"><a href="#"><?= htmlspecialchars($post['category']) ?></a></li>
            <li class="breadcrumb-item active" aria-current="page"><?= htmlspecialchars($post['title']) ?></li>
        </ol>
    </nav>

    <div class="row d-flex justify-content-between">

        <!-- EN-TETE ARTICLE  -->
        <div class="col-md-7 bg-white rounded p-4 border">
            <h1 class="fs-1 mb-3"><?= htmlspecialchars($post['title']) ?></h1>
            <h3 clas="fs-1">Dans la catégorie: <span class="text-danger"><?= htmlspecialchars($post['category']) ?></span></h3>
            <span class="d-block"><i class="fas fa-glasses me-2"></i><em>Rédigé par <b><?= htmlspecialchars($post['firstname']).' '.htmlspecialchars($post['lastname']) ?></b> le <?= htmlspecialchars($post['created_at']) ?></em></span>

            <!-- Contenu de l'article  -->
            <p class="my-4 opacity-75"><?= htmlspecialchars($post['content']) ?></p>
        </div>

        <div class="comments bg-white col-md-4 border py-3 rounded border-bottom">
            <strong class="d-block text-center py-2">Liste des commentaires (<?= htmlspecialchars($total_comments['total']) ?>)</strong>
            <hr>
            <div class="comments-container rounded p-3">

                <?php if($total_comments['total'] >= 1): ?>
                    
                    <?php foreach($comments as $comment): ?>
                    <div>
                        <span><i class="far fa-comment-dots"> </i> Ecrit par: <?= htmlspecialchars($comment['nickname']) ?></span>
                        <p class="opacity-50"><?= htmlspecialchars($comment['content']) ?></p>
                    </div>
                    <hr class="text-dark">
                    <?php endforeach ?>

                <?php else: ?>
                    <p class="opacity-50 text-center mt-5">Pas de commentaires pour cet article</p>

                <?php endif ?>
            </div>
            <hr>
            
            <!-- FORMULAIRE  -->
            <form action="<?= $_SERVER['REQUEST_URI'] ?>" method="POST">
                
                <div class="container-msg my-2">

                    <!-- MESSAGE SUCCESS  -->
                    <?php if(isset($_SESSION['success']) && !empty($_SESSION['success'])): ?>
                    <div class="alert alert-success text-center" id="js-success" role="alert">
                        <?= $commentInstance->getSuccessFeedback('addSuccess') ?>
                    </div>
                    <?php endif ?>

                </div>

                <!-- Input Pseudo -->
                <div class="mb-2">
                    <input type="text" name="pseudo" class="form-control" placeholder="Choisissez un pseudo" value="<?= (isset($_POST['pseudo'])) ? htmlspecialchars($_POST['pseudo']) : '' ?>">

                    <!-- MESSAGE ERROR  -->
                    <div class="text-center" style="min-height: 25px">
                        <?= $commentInstance->getInvalidFeedback('pseudo') ?>
                    </div>
                </div>

                <!-- Textarea Commentaire  -->
                <div>
                    <textarea name="comment" class="form-control" rows="2" placeholder="Votre commentaire..."><?= (isset($_POST['comment'])) ? htmlspecialchars($_POST['comment']) : '' ?></textarea>

                    <!-- MESSAGE ERROR  -->
                    <div class="text-center" style="min-height: 25px">
                        <?= $commentInstance->getInvalidFeedback('comment') ?>
                    </div>
                </div>
                
                <!-- Bouton d'envoi -->
                <div class="text-center mt-2">
                    <button type="submit" name="addComment" class="btn btn-dark">Envoyer</button>
                </div>
            </form>
        </div>
    </div>

</div>