<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item">Administration</li>
            <li class="breadcrumb-item active" aria-current="page">Gestion des articles</li>
        </ol>
    </nav>
</div>
<div class="container admin grid-admin">

    <?php include '../Views/admin/partials/_nav.phtml' ?>
    
    <div class="bg-white rounded shadow-sm p-3">
        <h1 class="text-center mb-5">Gestion des articles</h1>
        <hr>
        <a href="index.php?page=create" class="btn btn-success my-2"><i class="fas fa-plus pe-2"></i>Créer un article</a>
        <table class="table table-striped bg-white">
            <thead class="bg-dark text-light">
                <tr>
                    <th>ID</th>
                    <th>Création</th>
                    <th>Titre</th>
                    <th>Auteur</th>
                    <th>Catégorie</th>
                    <th class="text-end">Opérations</th>
                </tr>
             </thead>
            <tbody>
                <?php foreach ($posts as $post): ?>
                <tr>
                    <!-- ID  -->
                    <td class="fw-bold"><?= htmlspecialchars($post['id']) ?></td>
                    <!-- DATE  -->
                    <td><em><?= htmlspecialchars($post['created_at']) ?></em></td>
                    <!-- ARTICLE URL + TITRE  -->
                    <td><?= substr(htmlspecialchars($post['title']), 0, 25) ?> [...]</td>
                    <!-- AUTEUR  -->
                    <td><?= htmlspecialchars($post['firstname'])." ".htmlspecialchars($post['lastname']) ?></td>
                    <!-- CATEGORIE  -->
                    <td><?= htmlspecialchars($post['category']) ?></td>
                    <!-- OPERATIONS  -->
                    <td class="col-3 text-end">
                        <!-- DETAILS ARTICLE  -->
                        <a href="index.php?page=post&id=<?= htmlspecialchars($post['id']) ?>" class="link-info mx-1" title="Détails de l'article"><i class="fas fa-search-plus fs-3"></i></a>
                        <!-- EDITION ARTICLE  -->
                        <a href="index.php?page=edit&id=<?= htmlspecialchars($post['id']) ?>" class="link-warning mx-1" title="Modification de l'article"><i class="fas fa-edit fs-3"></i></a>
                        <!-- SUPPRESSION ARTICLE  -->
                        <button data-bs-toggle="modal" data-bs-target="#delete-modal-<?= intval($post['id']) ?>" class="text-danger border-0 bg-transparent" title="Suppression de l'article"><i class="fas fa-trash fs-1"></i></button>

                        <!-- Modal -->
                        <div class="modal fade" id="delete-modal-<?= intval($post['id']) ?>" tabindex="-1" aria-labelledby="delete-confirm" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="delete-confirm">Voulez vous vraiment supprimer cet article ?</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Annuler</button>
                                    <a href="index.php?page=delete&id=<?= intval($post['id']) ?>" class="btn btn-danger">Confirmer</a>
                                </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <figcaption>Liste des posts classés par ordre chronologique inversé (<b><?= htmlspecialchars($total['total']) ?> <?= ($total['total'] <= 1) ? "article" : "articles" ; ?> au total</b>)</figcaption>
    </div>
</div>


