<nav class="bg-white rounded shadow-sm text-center">
    <ul class="pt-4">
        <li class="mb-3"><a href="index.php?page=admin" class="active-nav"><i class="fas fa-newspaper me-2"></i> Gestion des articles</a></li>
        <li class="mb-3"><a href="#"><i class="fas fa-tags me-2"></i> Gestion des catégories</a></li>
        <li class="mb-3"><a href="#"><i class="fas fa-users me-2"></i> Gestion des auteurs</a></li>
    </ul>
</nav>